### ISSUE TITLE
help...

### ISSUE THREAD

**Issue by random-robbie** [skerit/stbroker#1]
this might be me as i dont know nodejs (more of a php guy)

I've copied your example and ran npm install stbroker.

I added require at the top also.

```
/root/stb.js:2
var iptv = new stbroker({
               ^
ReferenceError: stbroker is not defined
    at Object.<anonymous> (/root/stb.js:2:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Function.Module.runMain (module.js:497:10)
    at startup (node.js:119:16)
    at node.js:902:3
root@mepc:~#
```

Can you help?

**Comment by prikshitgupta** [comment]
Add the following line on top of your file:

`const Stbroker = require("stbroker");`
