### ISSUE TITLE
Issue Protoblast

### ISSUE THREAD

**Issue by domaincowley** [skerit/stbroker#2]
Hi,

Get the following error 

node_modules\stbroker\node_modules\protoblast\lib\url.js:103
                temp = document.createElement('a');

Using nodejs server 

Thanks,

**Comment by scope-username** [comment]
facing the same issue. Attached my logs below.

```
$ node script.js
/Users/a/Documents/test/node_modules/protoblast/lib/url.js:103
                temp = document.createElement('a');
                ^

ReferenceError: document is not defined
    at URL.parse (/Users/a/Documents/test/node_modules/protoblast/lib/url.js:103:3)
    at new URL (/Users/a/Documents/test/node_modules/protoblast/lib/url.js:37:10)
    at Object.parse (/Users/a/Documents/test/node_modules/protoblast/lib/url.js:139:13)
    at Stbroker.http_request (/Users/a/Documents/test/node_modules/stbroker/lib/init.js:116:13)
    at Stbroker._request (/Users/a/Documents/test/node_modules/stbroker/lib/init.js:235:7)
    at Stbroker.getPortalUrl (/Users/a/Documents/test/node_modules/stbroker/lib/init.js:376:7)
    at new Stbroker (/Users/a/Documents/test/node_modules/stbroker/lib/init.js:53:7)
    at Object.<anonymous> (/Users/a/Documents/test/script.js:3:14)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
```
